### ISSUE TITLE
Failling to parse database valid keywords

### ISSUE THREAD

**Issue by oferbu** [duythinht/dbml-go#9]
Hello,

In case the DBML file has problematic yet valid words such as key, project or action the parser fails to parse the file

**Comment by duythinht** [comment]
hi @oferbu can you provide an example?

**Comment by oferbu** [comment]
Hi @duythinht, 
here are some examples (sorry i can't share the original tables` definition)

// parsing "progress" problem example 

```
Table YYY1 {
    columnXYZ int 
    columnXYZ int 
===>    progress tinyint [ not null ]
}
```
======================================================================

// parsing "type" as key problem example 
```
Table YYY2 {
    type char(16) [ default: '0' ]
    columnXYZ int
    columnXYZ int 

    indexes {
==>   (type) [pk]}
}
```
======================================================================

// parsing "key" as key problem example
```
Table YYY3 {
    key varchar(128) 
    value text(65535) [ not null ]

    indexes {
>>>    (key) [name: 'key_UNIQUE']
>>>    (key) [pk]}
}
```
======================================================================

// parsing "Project" as table name problem example 
```
>>> Table Project {
    columnXYZ int 
    columnXYZ int   
    columnXYZ int   
}
```
======================================================================

// parsing "action" as field name in index problem example 
```
Table YYY4 {
    columnXYZ int 
    columnXYZ int 
    columnXYZ int  

    indexes {

>>>    (colXYZ, action) [name: 'bbbb', unique]
}
```
======================================================================

// parsing "key" as key problem example
```
Table YYY5 {
    Hash varchar(45)
    Key varchar(128)
    Value varchar(2048)

    indexes {
>>>   (Hash, Key) [pk]}
}
```


// parsing "section" as key problem example 
```
Table YYY6 {
    columnXYZ int 
    Section varchar(50) [ not null ]
    Key varchar(50) [ not null ]
    columnXYZ int 
    columnXYZ int 

    indexes {
>>>    (Section, Key) [name: 'aaaaa', unique]
    }
}
```

**Comment by oferbu** [comment]
hey @duythinht, any update on the above?

**Comment by oferbu** [comment]
for anyone who is interested there is a fix for the above bug at https://github.com/oferbu/dbml-go/commits/master

**Comment by duythinht** [comment]
Sorry for lately response, due to some health issue, this one already fixed and allow for all keyword could be produce as identity
https://github.com/duythinht/dbml-go/pull/10
